### ISSUE TITLE
درخواست متد در رابطه با لیست خوانشها

### ISSUE THREAD

**Issue by ham3da** [ganjoor/GanjoorService#210]
<div dir="rtl">
با سلام و عرض ادب و سپاس بیکران از زحمات شما دوستان بزرگوار<br>
درخواست می کنم در صورت امکان متدهای زیر را  به سرویس گنجور اضافه نمایید:

1. متد دریافت لیست خوانشهای مربوط به یک شاعر مثل حافظ
2. متد دریافت  لیست خوانشهای مربوط به یک مجموعه شعر مثل غزلیات حافظ
</div>

**Comment by hrmoh** [comment]
متدهای مد نظر اضافه شد.
پس از انتشار و اطمینان از درستی کارکرد به شما اطلاع می‌دهم.
ممکن است تا چند روزی طول بکشد.
