### ISSUE TITLE
use HTML audio instead of jplayer for playing recitations

### ISSUE THREAD

**Issue by hrmoh** [ganjoor/GanjoorService#250]

**Comment by ehsanghaffarii** [comment]
I was introduced to this web service today. Your work is excellent
If you want help, it's me

**Comment by hrmoh** [comment]
> I was introduced to this web service today. Your work is excellent If you want help, it's me

Thanks for your kind words and interest. Please consider some suggested good first issues introduced in some projects including this one (vue.js):
[https://github.com/ganjoor/abjad/issues?q=label%3A%22good+first+issue%22+is%3Aissue+is%3Aopen](https://github.com/ganjoor/abjad/issues?q=label%3A%22good+first+issue%22+is%3Aissue+is%3Aopen)
Thanks!
