### ISSUE TITLE
Tooltip text from utility buttons obscures 3 adjacent buttons

### ISSUE THREAD

**Issue by a-pav** [ganjoor/GanjoorService#446]
This is how tooltips are currently shown:
![image](https://github.com/user-attachments/assets/81902dee-4980-4891-9970-852230e39832)

While this tooltip is showing, you can't access its adjacent buttons. To do so, you have to move the mouse/pointer away and then return to those buttons again after the tooltip has disappeared.

I'm not sure what's the best CSS solution for this, but this is my current personal fix:
```js
// Fix tooltips on-hover positions.
document.querySelector('div.utilbar').style.paddingTop = '25px'
// Append `transform` CSS prop to already defined stylesheet.
const sheet = document.styleSheets[0];
sheet.insertRule(`
	.w3tooltip:hover .w3tooltiptext {
		transform:  translateY(-20px);
	}`, sheet.cssRules.length
)
```

this makes the tooltips show like:
![image](https://github.com/user-attachments/assets/2f03bac2-37ce-4ed7-ae87-d5accf8133a9)

Which is much better.

**Comment by hrmoh** [comment]
Thanks for mentioning this irritating bug, I removed w3tooltips and replaces them with anchor title.


> This is how tooltips are currently shown: ![image](https://private-user-images.githubusercontent.com/14939129/376524706-81902dee-4980-4891-9970-852230e39832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODY5MjQsIm5iZiI6MTcyOTA4NjYyNCwicGF0aCI6Ii8xNDkzOTEyOS8zNzY1MjQ3MDYtODE5MDJkZWUtNDk4MC00ODkxLTk5NzAtODUyMjMwZTM5ODMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEzNTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZGFhMzRkZWRmNjY2MDYwYzhhNzFmYThmMmU5MjNiY2VkMTBiY2NiNjBlM2Q0OGU0NGExYzQ1MjMyMmNlZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QY_akBq6gAwnKdt5yRsbRRrHMfYHdJRZJyUZOr6mDPU)
> 
> While this tooltip is showing, you can't access its adjacent buttons. To do so, you have to move the mouse/pointer away and then return to those buttons again after the tooltip has disappeared.
> 
> I'm not sure what's the best CSS solution for this, but this is my current personal fix:
> 
> ```js
> // Fix tooltips on-hover positions.
> document.querySelector('div.utilbar').style.paddingTop = '25px'
> // Append `transform` CSS prop to already defined stylesheet.
> const sheet = document.styleSheets[0];
> sheet.insertRule(`
> 	.w3tooltip:hover .w3tooltiptext {
> 		transform:  translateY(-20px);
> 	}`, sheet.cssRules.length
> )
> ```
> 
> this makes the tooltips show like: ![image](https://private-user-images.githubusercontent.com/14939129/376528675-2f03bac2-37ce-4ed7-ae87-d5accf8133a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODY5MjQsIm5iZiI6MTcyOTA4NjYyNCwicGF0aCI6Ii8xNDkzOTEyOS8zNzY1Mjg2NzUtMmYwM2JhYzItMzdjZS00ZWQ3LWFlODctZDVhY2NmODEzM2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEzNTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjUxNzE3NGM5NjE3M2JjN2MwZjNiZThiYjkzNGMzOGEwMjFkMjNmZTk2YmY2OTUwZGU3MDM3YTZjYzA1NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NKyidSC-ITgneCiJTEdR8mEwfnwRYhuO1Ema2X9LYk8)
> 
> Which is much better.
